import {
  CategorySales,
  Customer,
  DashboardSummary,
  MonthlyRevenue,
  OrderStatusData,
  Product,
  RegionSales,
  Report,
  Sale,
} from '../types/sales';

export const MOCK_SUMMARY: DashboardSummary = {
  totalRevenue: 1248500,
  totalOrders: 324,
  totalCustomers: 142,
  averageOrderValue: 3853,
};

export const MOCK_MONTHLY_REVENUE: MonthlyRevenue[] = [
  { month: 'Jan', revenue: 64200 },
  { month: 'Feb', revenue: 78500 },
  { month: 'Mar', revenue: 92400 },
  { month: 'Apr', revenue: 86100 },
  { month: 'May', revenue: 104500 },
  { month: 'Jun', revenue: 118200 },
  { month: 'Jul', revenue: 112000 },
  { month: 'Aug', revenue: 129400 },
  { month: 'Sep', revenue: 138000 },
  { month: 'Oct', revenue: 146800 },
  { month: 'Nov', revenue: 162500 },
  { month: 'Dec', revenue: 185400 },
];

export const MOCK_CATEGORY_SALES: CategorySales[] = [
  { category: 'Enterprise Tech', sales: 438000 },
  { category: 'Cloud Infrastructure', sales: 312000 },
  { category: 'Hardware & Workstations', sales: 245000 },
  { category: 'Security & Compliance', sales: 154500 },
  { category: 'Support & SLAs', sales: 99000 },
];

export const MOCK_REGION_SALES: RegionSales[] = [
  { region: 'North', sales: 384000 },
  { region: 'South', sales: 326000 },
  { region: 'West', sales: 279500 },
  { region: 'East', sales: 168000 },
  { region: 'Central', sales: 91000 },
];

export const MOCK_ORDER_STATUS: OrderStatusData = {
  summary: {
    Completed: 254,
    Pending: 48,
    Cancelled: 22,
  },
  list: [
    { status: 'Completed', count: 254 },
    { status: 'Pending', count: 48 },
    { status: 'Cancelled', count: 22 },
  ],
};

export const MOCK_SALES: Sale[] = [
  {
    id: 101,
    customerId: 1,
    customer: 'Apex Global Industries',
    customerEmail: 'procurement@apexglobal.com',
    date: '2026-03-22',
    amount: 84500,
    status: 'Completed',
    region: 'North',
    itemsCount: 6,
  },
  {
    id: 102,
    customerId: 2,
    customer: 'Zenith Financial Corp',
    customerEmail: 'ops@zenithcorp.org',
    date: '2026-03-21',
    amount: 142000,
    status: 'Completed',
    region: 'South',
    itemsCount: 12,
  },
  {
    id: 103,
    customerId: 3,
    customer: 'OmniCorp Logistics',
    customerEmail: 'billing@omnicorp.io',
    date: '2026-03-20',
    amount: 49000,
    status: 'Pending',
    region: 'West',
    itemsCount: 4,
  },
  {
    id: 104,
    customerId: 4,
    customer: 'Hyperion Biotech Ltd',
    customerEmail: 'contact@hyperionbio.com',
    date: '2026-03-19',
    amount: 198000,
    status: 'Completed',
    region: 'North',
    itemsCount: 15,
  },
  {
    id: 105,
    customerId: 5,
    customer: 'Vanguard Media Group',
    customerEmail: 'finance@vanguardmg.com',
    date: '2026-03-18',
    amount: 32500,
    status: 'Completed',
    region: 'East',
    itemsCount: 3,
  },
  {
    id: 106,
    customerId: 6,
    customer: 'Starlight Retail Partners',
    customerEmail: 'orders@starlightretail.in',
    date: '2026-03-17',
    amount: 76000,
    status: 'Pending',
    region: 'Central',
    itemsCount: 8,
  },
  {
    id: 107,
    customerId: 7,
    customer: 'Solaris Aerospace Inc',
    customerEmail: 'contracts@solaris-aero.com',
    date: '2026-03-15',
    amount: 235000,
    status: 'Completed',
    region: 'South',
    itemsCount: 18,
  },
  {
    id: 108,
    customerId: 8,
    customer: 'Nexus Automations',
    customerEmail: 'accounts@nexusauto.co',
    date: '2026-03-14',
    amount: 15400,
    status: 'Cancelled',
    region: 'West',
    itemsCount: 2,
  },
  {
    id: 109,
    customerId: 9,
    customer: 'Aura Software Labs',
    customerEmail: 'admin@aurasoft.dev',
    date: '2026-03-12',
    amount: 62000,
    status: 'Completed',
    region: 'North',
    itemsCount: 5,
  },
  {
    id: 110,
    customerId: 10,
    customer: 'Equinox Capital Partners',
    customerEmail: 'trade@equinoxcap.com',
    date: '2026-03-10',
    amount: 115000,
    status: 'Completed',
    region: 'South',
    itemsCount: 9,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Enterprise Cloud Suite Pro',
    category: 'Cloud Infrastructure',
    price: 36000,
    stock: 150,
    unitsSold: 94,
    revenue: 338400,
  },
  {
    id: 2,
    name: 'Precision High-Compute Server R7',
    category: 'Hardware & Workstations',
    price: 85000,
    stock: 35,
    unitsSold: 28,
    revenue: 238000,
  },
  {
    id: 3,
    name: 'Zero-Trust SOC Shield Gateway',
    category: 'Security & Compliance',
    price: 24500,
    stock: 80,
    unitsSold: 63,
    revenue: 154350,
  },
  {
    id: 4,
    name: 'Distributed Data Lake Cluster',
    category: 'Enterprise Tech',
    price: 49000,
    stock: 45,
    unitsSold: 37,
    revenue: 181300,
  },
  {
    id: 5,
    name: 'UltraWide Curved Analyst Display 40"',
    category: 'Hardware & Workstations',
    price: 18500,
    stock: 60,
    unitsSold: 42,
    revenue: 77700,
  },
  {
    id: 6,
    name: 'Tier-1 Mission Critical SLA 24/7',
    category: 'Support & SLAs',
    price: 15000,
    stock: 200,
    unitsSold: 66,
    revenue: 99000,
  },
  {
    id: 7,
    name: 'Automated Regulatory Compliance Kit',
    category: 'Security & Compliance',
    price: 22000,
    stock: 90,
    unitsSold: 41,
    revenue: 90200,
  },
  {
    id: 8,
    name: 'AI Pipeline Inference Accelerator',
    category: 'Enterprise Tech',
    price: 58000,
    stock: 25,
    unitsSold: 19,
    revenue: 110200,
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 1,
    name: 'Apex Global Industries',
    email: 'procurement@apexglobal.com',
    phone: '+91 98201 44521',
    region: 'North',
    totalOrders: 18,
    totalSpending: 284500,
  },
  {
    id: 2,
    name: 'Zenith Financial Corp',
    email: 'ops@zenithcorp.org',
    phone: '+91 98402 77192',
    region: 'South',
    totalOrders: 24,
    totalSpending: 392000,
  },
  {
    id: 3,
    name: 'Solaris Aerospace Inc',
    email: 'contracts@solaris-aero.com',
    phone: '+91 98711 33284',
    region: 'South',
    totalOrders: 14,
    totalSpending: 235000,
  },
  {
    id: 4,
    name: 'Hyperion Biotech Ltd',
    email: 'contact@hyperionbio.com',
    phone: '+91 98110 59203',
    region: 'North',
    totalOrders: 12,
    totalSpending: 198000,
  },
  {
    id: 5,
    name: 'Equinox Capital Partners',
    email: 'trade@equinoxcap.com',
    phone: '+91 98223 88102',
    region: 'South',
    totalOrders: 9,
    totalSpending: 115000,
  },
  {
    id: 6,
    name: 'OmniCorp Logistics',
    email: 'billing@omnicorp.io',
    phone: '+91 98334 12093',
    region: 'West',
    totalOrders: 11,
    totalSpending: 96400,
  },
  {
    id: 7,
    name: 'Starlight Retail Partners',
    email: 'orders@starlightretail.in',
    phone: '+91 98450 67123',
    region: 'Central',
    totalOrders: 8,
    totalSpending: 76000,
  },
  {
    id: 8,
    name: 'Aura Software Labs',
    email: 'admin@aurasoft.dev',
    phone: '+91 98192 45678',
    region: 'North',
    totalOrders: 7,
    totalSpending: 62000,
  },
];

export const MOCK_REPORTS: Report = {
  totalRevenue: 1248500,
  totalOrders: 324,
  topCategory: 'Enterprise Tech',
  topRegion: 'North',
  topProduct: 'Enterprise Cloud Suite Pro',
  topProductRevenue: 338400,
  summaryTable: [
    {
      region: 'North',
      totalOrders: 112,
      completedOrders: 96,
      totalRevenue: 384000,
    },
    {
      region: 'South',
      totalOrders: 94,
      completedOrders: 82,
      totalRevenue: 326000,
    },
    {
      region: 'West',
      totalOrders: 68,
      completedOrders: 54,
      totalRevenue: 279500,
    },
    {
      region: 'East',
      totalOrders: 34,
      completedOrders: 28,
      totalRevenue: 168000,
    },
    {
      region: 'Central',
      totalOrders: 16,
      completedOrders: 14,
      totalRevenue: 91000,
    },
  ],
  financialMetrics: {
    grossRevenue: 1248500,
    cogs: 499400,
    grossProfit: 749100,
    grossMarginPercent: '60.0%',
    operatingExpenses: 312000,
    netOperatingIncome: 437100,
    netMarginPercent: '35.0%',
    collectionsRate: '94.2%',
  },
  operatingExpenses: [
    {
      id: 1,
      category: 'Cloud Infrastructure & Hosting',
      department: 'DevOps & Reliability',
      amount: 112000,
      budgetedAmount: 120000,
      variance: -8000,
      quarter: 'Q1-2026',
    },
    {
      id: 2,
      category: 'Sales Commission & Incentives',
      department: 'Enterprise Sales',
      amount: 86500,
      budgetedAmount: 85000,
      variance: 1500,
      quarter: 'Q1-2026',
    },
    {
      id: 3,
      category: 'Security Audits & Compliance Tooling',
      department: 'InfoSec & Legal',
      amount: 48000,
      budgetedAmount: 50000,
      variance: -2000,
      quarter: 'Q1-2026',
    },
    {
      id: 4,
      category: 'Marketing & Digital Acquisition',
      department: 'Growth Marketing',
      amount: 39500,
      budgetedAmount: 45000,
      variance: -5500,
      quarter: 'Q1-2026',
    },
    {
      id: 5,
      category: 'Customer Support Escalation SLAs',
      department: 'Customer Success',
      amount: 26000,
      budgetedAmount: 25000,
      variance: 1000,
      quarter: 'Q1-2026',
    },
  ],
  executiveReviews: [
    {
      quarter: 'Q1-2026',
      revenueTarget: 1200000,
      actualRevenue: 1248500,
      cogs: 499400,
      operatingExpenses: 312000,
      netProfit: 437100,
      growthRate: '+18.4% YoY',
      strategicHighlights:
        'North region enterprise tech adoption beat projections by 14%. Cloud Suite Pro reached peak contract renewal rate at 94.2%.',
      operationalRisks:
        'Escrow clearance velocity in West region requires tighter SLA monitoring. Supply lead times for server chassis stable.',
      auditorSignoff: 'PWC Corporate Assurance (Approved)',
      auditDate: '2026-03-20',
    },
    {
      quarter: 'Q4-2025',
      revenueTarget: 1050000,
      actualRevenue: 1115000,
      cogs: 457150,
      operatingExpenses: 289000,
      netProfit: 368850,
      growthRate: '+15.2% YoY',
      strategicHighlights:
        'Annual holiday and fiscal close expansion closed 4 Tier-1 enterprise multi-year retainers.',
      operationalRisks:
        'Higher travel costs during client summits absorbed 4% of Q4 discretionary sales allocation.',
      auditorSignoff: 'Internal Audit Oversight (Approved)',
      auditDate: '2025-12-28',
    },
  ],
  enterpriseContracts: [
    {
      id: 1,
      contractCode: 'AGI-2026-09A',
      clientName: 'Apex Global Industries',
      tier: 'Strategic Enterprise',
      dealValue: 284500,
      terms: '36 Mo Multi-Year',
      paymentStatus: 'Settled',
      settlementDate: '2026-03-22',
      region: 'North',
    },
    {
      id: 2,
      contractCode: 'ZFC-2026-14B',
      clientName: 'Zenith Financial Corp',
      tier: 'High Value Core',
      dealValue: 392000,
      terms: '24 Mo SLA Retainer',
      paymentStatus: 'Settled',
      settlementDate: '2026-03-21',
      region: 'South',
    },
    {
      id: 3,
      contractCode: 'SAI-2026-03X',
      clientName: 'Solaris Aerospace Inc',
      tier: 'Defense & Aerospace',
      dealValue: 235000,
      terms: '12 Mo Advance Annual',
      paymentStatus: 'Settled',
      settlementDate: '2026-03-15',
      region: 'South',
    },
    {
      id: 4,
      contractCode: 'HBL-2026-88C',
      clientName: 'Hyperion Biotech Ltd',
      tier: 'Strategic Enterprise',
      dealValue: 198000,
      terms: '24 Mo Milestones',
      paymentStatus: 'In Escrow',
      settlementDate: '2026-03-19',
      region: 'North',
    },
    {
      id: 5,
      contractCode: 'OCL-2026-05E',
      clientName: 'OmniCorp Logistics',
      tier: 'Standard Enterprise',
      dealValue: 96400,
      terms: 'Net 30 Days',
      paymentStatus: 'Invoice Sent',
      settlementDate: '2026-03-20',
      region: 'West',
    },
    {
      id: 6,
      contractCode: 'EQC-2026-21M',
      clientName: 'Equinox Capital Partners',
      tier: 'High Value Core',
      dealValue: 115000,
      terms: '12 Mo Quarterly Settle',
      paymentStatus: 'Settled',
      settlementDate: '2026-03-10',
      region: 'South',
    },
  ],
};
